/*
 * Titan API
 * API used by the Titan CLI
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CommitStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-19T12:42:23.490528-04:00[America/New_York]")
public class CommitStatus {
  public static final String SERIALIZED_NAME_LOGICAL_SIZE = "logicalSize";
  @SerializedName(SERIALIZED_NAME_LOGICAL_SIZE)
  private Long logicalSize;

  public static final String SERIALIZED_NAME_ACTUAL_SIZE = "actualSize";
  @SerializedName(SERIALIZED_NAME_ACTUAL_SIZE)
  private Long actualSize;

  public static final String SERIALIZED_NAME_UNIQUE_SIZE = "uniqueSize";
  @SerializedName(SERIALIZED_NAME_UNIQUE_SIZE)
  private Long uniqueSize;

  public static final String SERIALIZED_NAME_READY = "ready";
  @SerializedName(SERIALIZED_NAME_READY)
  private Boolean ready;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;


  public CommitStatus logicalSize(Long logicalSize) {
    
    this.logicalSize = logicalSize;
    return this;
  }

   /**
   * Logical size of data referenced by commit
   * @return logicalSize
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Logical size of data referenced by commit")

  public Long getLogicalSize() {
    return logicalSize;
  }


  public void setLogicalSize(Long logicalSize) {
    this.logicalSize = logicalSize;
  }


  public CommitStatus actualSize(Long actualSize) {
    
    this.actualSize = actualSize;
    return this;
  }

   /**
   * Actual size of data referenced by commit
   * @return actualSize
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Actual size of data referenced by commit")

  public Long getActualSize() {
    return actualSize;
  }


  public void setActualSize(Long actualSize) {
    this.actualSize = actualSize;
  }


  public CommitStatus uniqueSize(Long uniqueSize) {
    
    this.uniqueSize = uniqueSize;
    return this;
  }

   /**
   * Amount of data uniquely held by this commit
   * @return uniqueSize
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Amount of data uniquely held by this commit")

  public Long getUniqueSize() {
    return uniqueSize;
  }


  public void setUniqueSize(Long uniqueSize) {
    this.uniqueSize = uniqueSize;
  }


  public CommitStatus ready(Boolean ready) {
    
    this.ready = ready;
    return this;
  }

   /**
   * Whether this commit can be used as the source of an operation or whether it&#39;s still being created
   * @return ready
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Whether this commit can be used as the source of an operation or whether it's still being created")

  public Boolean getReady() {
    return ready;
  }


  public void setReady(Boolean ready) {
    this.ready = ready;
  }


  public CommitStatus error(String error) {
    
    this.error = error;
    return this;
  }

   /**
   * If commit failed to be created, error string explaining why
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If commit failed to be created, error string explaining why")

  public String getError() {
    return error;
  }


  public void setError(String error) {
    this.error = error;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitStatus commitStatus = (CommitStatus) o;
    return Objects.equals(this.logicalSize, commitStatus.logicalSize) &&
        Objects.equals(this.actualSize, commitStatus.actualSize) &&
        Objects.equals(this.uniqueSize, commitStatus.uniqueSize) &&
        Objects.equals(this.ready, commitStatus.ready) &&
        Objects.equals(this.error, commitStatus.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logicalSize, actualSize, uniqueSize, ready, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitStatus {\n");
    sb.append("    logicalSize: ").append(toIndentedString(logicalSize)).append("\n");
    sb.append("    actualSize: ").append(toIndentedString(actualSize)).append("\n");
    sb.append("    uniqueSize: ").append(toIndentedString(uniqueSize)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

