/*
 * Titan API
 * API used by the Titan CLI
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RepositoryStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-19T12:42:23.490528-04:00[America/New_York]")
public class RepositoryStatus {
  public static final String SERIALIZED_NAME_LAST_COMMIT = "lastCommit";
  @SerializedName(SERIALIZED_NAME_LAST_COMMIT)
  private String lastCommit;

  public static final String SERIALIZED_NAME_SOURCE_COMMIT = "sourceCommit";
  @SerializedName(SERIALIZED_NAME_SOURCE_COMMIT)
  private String sourceCommit;


  public RepositoryStatus lastCommit(String lastCommit) {
    
    this.lastCommit = lastCommit;
    return this;
  }

   /**
   * The latest commit ID for the repository
   * @return lastCommit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The latest commit ID for the repository")

  public String getLastCommit() {
    return lastCommit;
  }


  public void setLastCommit(String lastCommit) {
    this.lastCommit = lastCommit;
  }


  public RepositoryStatus sourceCommit(String sourceCommit) {
    
    this.sourceCommit = sourceCommit;
    return this;
  }

   /**
   * The source commit for the current state (last checkout or commit)
   * @return sourceCommit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The source commit for the current state (last checkout or commit)")

  public String getSourceCommit() {
    return sourceCommit;
  }


  public void setSourceCommit(String sourceCommit) {
    this.sourceCommit = sourceCommit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryStatus repositoryStatus = (RepositoryStatus) o;
    return Objects.equals(this.lastCommit, repositoryStatus.lastCommit) &&
        Objects.equals(this.sourceCommit, repositoryStatus.sourceCommit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastCommit, sourceCommit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryStatus {\n");
    sb.append("    lastCommit: ").append(toIndentedString(lastCommit)).append("\n");
    sb.append("    sourceCommit: ").append(toIndentedString(sourceCommit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

