/*
 * Titan API
 * API used by the Titan CLI
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VolumeStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-19T12:42:23.490528-04:00[America/New_York]")
public class VolumeStatus {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_LOGICAL_SIZE = "logicalSize";
  @SerializedName(SERIALIZED_NAME_LOGICAL_SIZE)
  private Long logicalSize;

  public static final String SERIALIZED_NAME_ACTUAL_SIZE = "actualSize";
  @SerializedName(SERIALIZED_NAME_ACTUAL_SIZE)
  private Long actualSize;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Object properties;

  public static final String SERIALIZED_NAME_READY = "ready";
  @SerializedName(SERIALIZED_NAME_READY)
  private Boolean ready;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;


  public VolumeStatus name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Volume name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Volume name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public VolumeStatus logicalSize(Long logicalSize) {
    
    this.logicalSize = logicalSize;
    return this;
  }

   /**
   * Logical size consumed by the volume
   * @return logicalSize
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Logical size consumed by the volume")

  public Long getLogicalSize() {
    return logicalSize;
  }


  public void setLogicalSize(Long logicalSize) {
    this.logicalSize = logicalSize;
  }


  public VolumeStatus actualSize(Long actualSize) {
    
    this.actualSize = actualSize;
    return this;
  }

   /**
   * Actual (compressed) size used by the volume
   * @return actualSize
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Actual (compressed) size used by the volume")

  public Long getActualSize() {
    return actualSize;
  }


  public void setActualSize(Long actualSize) {
    this.actualSize = actualSize;
  }


  public VolumeStatus properties(Object properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Client-specific properties
   * @return properties
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Client-specific properties")

  public Object getProperties() {
    return properties;
  }


  public void setProperties(Object properties) {
    this.properties = properties;
  }


  public VolumeStatus ready(Boolean ready) {
    
    this.ready = ready;
    return this;
  }

   /**
   * True if the volume is ready for use in a runtime environmemnt
   * @return ready
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "True if the volume is ready for use in a runtime environmemnt")

  public Boolean getReady() {
    return ready;
  }


  public void setReady(Boolean ready) {
    this.ready = ready;
  }


  public VolumeStatus error(String error) {
    
    this.error = error;
    return this;
  }

   /**
   * Optional error message if volume asynchronously failed to be created
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional error message if volume asynchronously failed to be created")

  public String getError() {
    return error;
  }


  public void setError(String error) {
    this.error = error;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VolumeStatus volumeStatus = (VolumeStatus) o;
    return Objects.equals(this.name, volumeStatus.name) &&
        Objects.equals(this.logicalSize, volumeStatus.logicalSize) &&
        Objects.equals(this.actualSize, volumeStatus.actualSize) &&
        Objects.equals(this.properties, volumeStatus.properties) &&
        Objects.equals(this.ready, volumeStatus.ready) &&
        Objects.equals(this.error, volumeStatus.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, logicalSize, actualSize, properties, ready, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VolumeStatus {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    logicalSize: ").append(toIndentedString(logicalSize)).append("\n");
    sb.append("    actualSize: ").append(toIndentedString(actualSize)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

